### ISSUE TITLE
Davos doesn't work with Unified Authorization enabled

### ISSUE THREAD

**Issue by antondyachuk** [ForkPoint/davos#21] opened 2019-11-13 15:59 UTC
If Unified Authorization is enabled in instance as optional it is not possible to upload the data via davos using Business Manger user credentials
![image](https://user-images.githubusercontent.com/43670463/68780663-4b0beb00-063f-11ea-8c97-572fdf85a8fe.png)
Error: 
![image](https://user-images.githubusercontent.com/43670463/68780779-6c6cd700-063f-11ea-8cbd-4114429971a5.png)

**Comment by k2kirov** [comment] 2020-06-01 18:47
Hi @antondyachuk,
We'll take a look at this one and report back. Hopefully, it will be included in version 2.0

**Comment by k2kirov** [comment] 2020-06-26 17:59
Hi @antondyachuk the issue is fixed now with 2.0.0-alpha.12
You can specify the p12 certificate in the configuration and use it for Staging deployments.

Let me know if any problems occur.

**Closed by k2kirov** 2020-06-26 17:59 UTC
